version: "2.0"
services:
  bambulabs-aetrius-exporter:
    image: scooterstuff1/scooter-bambulabs-exporter
    env_file: .env
    container_name: bambulabs-scooter-exporter
    ports:
      - "9101:9101"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge
